# Generated by Django 3.1 on 2020-10-11 11:52

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djmail', '0002_auto_20161118_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.zoho.eu', max_length=1024, verbose_name='email host')),
                ('email_host_user', models.CharField(default='kontakt@danielkusy.email', max_length=1024, verbose_name='sender email')),
                ('sender_name', models.CharField(default='kontakt@danielkusy.email', max_length=256, verbose_name='sender name')),
                ('email_host_password', fernet_fields.fields.EncryptedTextField(default='j=oLEmW2dMHr~CFyU2iprcfob1MF.tUb', max_length=1024, verbose_name='email sender password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
