# Generated by Django 3.1 on 2020-09-08 12:02

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='example.imap.com', max_length=1024, verbose_name='email host')),
                ('email_host_user', models.CharField(default='user@example.com', max_length=1024, verbose_name='sender email')),
                ('sender_name', models.CharField(default='user@example.com', max_length=256, verbose_name='sender name')),
                ('email_host_password', fernet_fields.fields.EncryptedTextField(default='pass', max_length=1024, verbose_name='email sender password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
