name: django-auth-microservice

on:
  push:
    branches: [ master, develop, feature/deploy ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: dan-auth
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        touch /tmp
    - name: Run migrations and tests
      env:
        SECRET_KEY: secret
        ALLOWED_HOSTS: 127.0.0.1
        DB_NAME: dan-auth
        DB_USER: root
        DB_PASSWORD: pass
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        JWT_SIGNING_KEY_FILE_PATH: /tmp
      run: |
        python manage.py migrate
        pytest --ds=core.settings
